#############################
# deploy_sonarqube_iac #
#############################

app:
   name: sonarqube
   version: 9.1.0.47736
   os_user: sonar
   os_group: sonar
   folder: /opt/sonarqube
   port: 9000

url_package: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-{{ app.version }}.zip


package_list:
  - epel-release 
  - java-11-openjdk-devel

bashrc_env:
  - "export SONAR_JDBC_USERNAME="
  - "export SONAR_JDBC_PASSWORD="
  - "export SONAR_JDBC_URL="

security_limits_list:
  - "sonarqube   -   nofile   65536"  
  - "sonarqube   -   nproc    4096"  

firewall_list:
  - "{{ app.port }}/tcp"
