#############################
# deploy_sonarqube_iac #
#############################

app:
  name: sonarqube
  version: 9.3.0.51899
  os_user: sonar
  folder: /opt/sonarqube
  port: 9000

tmp_folder: /tmp 

url_package: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-{{ app.version }}.zip

bashrc_env:
  - "export SONAR_JDBC_USERNAME="
  - "export SONAR_JDBC_PASSWORD="
  - "export SONAR_JDBC_URL="

security_limits_list:
  - "{{ app.name }}   -   nofile   65536"  
  - "{{ app.name }}   -   nproc    4096"  

firewall_list:
  - "{{ app.port }}/tcp"
