---

- name: Bootstrap Sonarqube for Gitlab IAC 1
  hosts: all
  any_errors_fatal: true
  become: true   
  vars:
    package_list:
      - epel-release 
  roles: 
    - { role: rv-common, update_os: true }
    - { role: rv-common, download_bin: true } 
  tags: 
    - deploy_centos8
    - iac1

- name: Bootstrap Sonarqube for Gitlab IAC 2
  hosts: sonar
  any_errors_fatal: true
  become: true   
  vars:
    package_list:
      - java-11-openjdk-devel
      - zip
  roles: 
    - { role: rv-common, download_bin: true } 
    - { role: rv-common, adduser: true, os_user: "{{app.os_user}}" }     
    - { role: rv-common, security_limits: true } 
    - { role: rv-common, allowport: true }  
    - { role: rv-common, download_package: true }      
    - { role: sonar, setup_folder: true }  
    - { role: sonar, setup_startup: true }    
    # - { role: rv-common, setup_bashrc: true } 
  tags: 
    - deploy_centos8
    - iac2

# - name: Bootstrap Sonarqube for Gitlab IAC 3
#   hosts: sql
#   any_errors_fatal: true
#   become: true   
#   vars:  
#     package_list:
#       - psql
#   roles: 
#     - { role: rv-common, download_package: true } 
#     - { role: rv-common, download_bin: true } 
#     - { role: sonar, get_plugin: true } 
#   tags: 
#     - deploy_centos8
#     - iac3

