---

# This is for testing, test it first here...

- name: testing
  hosts: sonar
         #localhost ansible_user='{{ lookup("env", "ansible_user") }}' ansible_password='{{ lookup("env", "ansible_password") }}' gather_facts=no ansible_connection=local

  gather_facts: false
  # become: true
  vars:
    testy: "test"

  tasks: 
    # - shell: echo {{ groups['sonar'] }} 
    #   register: reg
    # - set_fact: 
    #     vm_name: '{{ reg.stdout | replace("[","") | replace("]","") }}'
    # - debug: 
    #     msg: "{{vm_name}}"   
    # - shell: echo {{ ansible_hostname }} > /tmp/host
    # - ping: 
    # - shell: ls /root
    #   become: true
    # - shell: echo "{{testy}}"
    #   register: reg
    # - debug: var=reg
    # - shell: cat /etc/security/limits.conf
    - shell: ls -la /tmp/*.zip
    
    
