---

- name: Check /opt/sonatype folder
  stat:
    path: /opt/sonatype
  register: file_info
  failed_when: file_info.stat.exists

- name: unarchive tar
  ansible.builtin.unarchive:
    src: /opt/nexus-{{ nexus_ver }}-unix.tar.gz
    dest: /opt
    remote_src: yes

- name: setup nexus folder
  shell: |
         mkdir -p /opt/sonatype
         mv /opt/nexus-"{{ nexus_ver }}" /opt/nexus
         mv /opt/nexus/ /opt/sonatype/
         mv /opt/sonatype-work/ /opt/sonatype/
 
- name: Create nexus script -without this IAC will not be possible
  template:
    src: nexus.sh.j2
    dest: "/opt/nexus.sh"
    mode: '0755' 
    owner: nexus
    group: nexus

- name: make run_as_user as nexus
  shell: |
         echo 'run_as_user="nexus"' > /opt/sonatype/nexus/bin/nexus.rc  

- name: change attribute and ownership
  include_tasks: chown.yml