---
  
- name: Restart sonar service
  ansible.builtin.systemd_service:
    state: restarted
    name: sonar
  notify: "Wait for sonar to start listening on port 9000"      

- name: Wait for sonar to start listening on port 9000
  ansible.builtin.wait_for:
    port: "{{ app.port }}"
    host: 0.0.0.0
    