---

- set_fact: 
    fail_if_exist: true
    archive_file: "{{tmp_folder}}/sonarqube-{{app.version}}.zip"
    folder: "{{app.folder}}"

- name: Check if {{app.folder}} exist
  include_role:
    name: rv-common
    tasks_from: fail_if_exist

- set_fact:
    folder: /opt
    unarchive: true

- name: Unarchive package
  include_role:
    name: rv-common
    tasks_from: unarchive 

- name: Rename sonarqube
  shell: "mv /opt/sonarqube-{{app.version}} {{app.folder}}"   

- set_fact:
    update_file: true
    folder_path: "{{app.folder}}/bin/linux-x86-64/sonar.sh"
    search_string: "#RUN_AS_USER="
    new_string: 'RUN_AS_USER="sonar"'  

- name: Set sonar as user
  include_role:
    name: rv-common
    tasks_from: update_file       

- set_fact:
    change_permission: true
    file_mode: 0755
    recursive: yes
    os_user: "{{ app.os_user }}"
    file_list:
      - "{{ app.folder }}"
    
- name: Change the permission recursively of app folder
  include_role:
    name: rv-common
    tasks_from: change_permission
    