---

- name: Create systemd sonar
  template:
    src: sonar.service.j2
    dest: "/etc/systemd/system/sonar.service"
    mode: '0755' 
    owner: root

- name: Daemon reload
  shell: systemctl daemon-reload    

- name: Start sonar service
  ansible.builtin.systemd_service:
    state: started
    name: sonar  

- name: Wait for sonar to start listening on port 9000
  ansible.builtin.wait_for:
    port: "{{ app.port }}"
    host: 0.0.0.0  
  ignore_errors: true    